---
- name: Install the Pip application
  package:
    name: "{{ pip_package_name }}"
    state: present

- name: Install specific Pip packages
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ pip_install_packages }}"
